[project]
name = "cltk"
version = "2.0.0a"
description = "The Classical Language Toolkit"
authors = [
    {name = "Kyle P. Johnson", email = "kyle@kyle-p-johnson.com"},
    {name = "Clément Besnier", email = "clem@clementbesnier.fr"},
]
readme = "README.rst"
homepage = "http://cltk.org"
repository = "https://github.com/cltk/cltk"
documentation = "https://docs.cltk.org"
keywords = ["nlp", "ai", "nltk", "latin", "greek", "sanskrit", "hebrew", "arabic", "chinese"]
requires-python = ">=3.11"
dependencies = [
    "tqdm (>=4.67.1,<5.0.0)",
    "openai (>=1.101.0,<2.0.0)",
    "python-dotenv (>=1.1.1,<2.0.0)",
    "pydantic (>=2.11.7,<3.0.0)",
    "colorama (>=0.4.6,<0.5.0)",
    "numpy (>=2.3.2,<3.0.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
[tool.poetry.group.development.dependencies]
mypy = "^1.17.1"
ipython = "^9.4.0"
pylint = "^3.3.8"
pylint-json2html = "^0.5.0"
black = "^25.1.0"
isort = "^6.0.1"
jupyter = "^1.1.1"
colorama = "^0.4.6"

